### ISSUE TITLE
ToC_PTR ?

### ISSUE THREAD

**Issue by Pocokk** [ForgeGit/Ulduar_PTR#3]
Hey there!

Do you plan to create a similar datasheet and do some nice graphs about the latest ToC PTR logs that were uploaded? (similarly to Ulduar)

Thank you in advance!

**Comment by ForgeGit** [comment]
Hey there! Just going back solving old pendings I have in my repositories.
Due to time constraints and other things happening I was never able to get back to you in a timely manner

I wasn't able to do anything for ToC PTR, however, ICC PTR data is available here:

https://github.com/ForgeGit/ICC_PTR

Hopefully I can keep making these in the future :) 

Thanks for always checking on the newest data in Private Messages.
